# Gopkg.toml for github.com/openshift/ci-ns-ttl-controller

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

